RestaurantMvc.Web/Controllers/ReservationController.cs
using System;
using System.Web;
using System.Web.Mvc;
using RestaurantMvc.Model.Models;
using RestaurantMvc.Reservation.Service;
using RestaurantMvc.ViewModel.ViewModels;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity.Owin;
using RestaurantMvc.Web.Models;


namespace RestaurantMvc.Web.Controllers
{
    public class ReservationController : Controller
    {
        private readonly IServiceReservation _serviceReservation;
        protected IdentityModels.ApplicationDbContext ApplicationDbContext { get; set; }
        protected UserManager<IdentityModels.ApplicationUser> UserManager { get; set; }
        public ReservationController()
        {
            _serviceReservation = new ReservationService();
            this.ApplicationDbContext = new IdentityModels.ApplicationDbContext();
            this.UserManager = new UserManager<IdentityModels.ApplicationUser>(new UserStore<IdentityModels.ApplicationUser>(this.ApplicationDbContext));
        }

        // GET: Reservation
        public ActionResult Index()
        {
            ViewBag.Title = "Please make reservation:";

            var isLogged = (System.Web.HttpContext.Current.User != null) &&
                           System.Web.HttpContext.Current.User.Identity.IsAuthenticated;
            if (!isLogged) return View();
            IdentityModels.ApplicationUser user = System.Web.HttpContext.Current.GetOwinContext().GetUserManager<ApplicationUserManager>().FindById(System.Web.HttpContext.Current.User.Identity.GetUserId());

            var reservationViewModel= new ReservationViewModel {Name = user.Name, Surname = user.Surname, Email = user.Email, PhoneNumber = user.PhoneNumber, ToWhatTime = new TimeSpan(23,0,0), FromWhatTime =  new TimeSpan(12,0,0),HowManyPeoples = 2};
            return View(reservationViewModel);
        }

        //POST:Reservation
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(ReservationViewModel reservation)
        {
            if (!ModelState.IsValid) return View();

            //if (reservation.ToWhatTime<reservation.FromWhatTime || !ModelState.IsValid)
            //{
            //    ViewBag.TimeStage = ReservationTimeStage.IsNotvalid;
            //    return View();
            //}
            //else
            //{
            //    ViewBag.TimeStage = ReservationTimeStage.IsValid;
            //}


            var preReservation = new PreReservationViewModel
            {
                FromWhatTime = reservation.FromWhatTime,
                ToWhatTime = reservation.ToWhatTime,
                ReservationDate = reservation.ReservationDate,
                HowManyPeoples = reservation.HowManyPeoples
            };
            try
            {
                var checkPrereservation = _serviceReservation.CheckPreReservation(preReservation);
                if (checkPrereservation)
                {
                    reservation.UserId = User.Identity.GetUserId();
                    TempData["Message"]= "ok";
                    _serviceReservation.ReserveTable(reservation);
                    return RedirectToAction("Index","Home");
                }
                else
                {
                    reservation.Status = OutputMessage.NoFreeTables;
                    return View(reservation);
                }
            }
            catch (Exception)
            {
                return View("Error");
            }
        }



       


    }
}

RestaurantMvc.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("~/Content/MyCss")
    @Styles.Render("~/Content/bootstrap-datetimepicker")
    @Styles.Render("~/Content/simple-sidebar")
    

</head>

<body>
<div class="navbar navbar-inverse navbar-fixed-top bartek" style="padding: 15px">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
                </button>
                @Html.ActionLink(" Home", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>

            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"></button>

                @Html.ActionLink(" Reservation", "Index", "Reservation", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"></button>

                @Html.ActionLink(" Menu", "Index", "Menu", new { area = "" }, new { @class = "navbar-brand" })
            </div>

            @Html.Partial("_LoginPartial")
        </div>
    </div>



    <br/>
    <br/>
    <div class="container body-content" style="padding: 15px">
        @{
            var controler = HttpContext.Current.Request.RequestContext.RouteData.Values["Controller"].ToString();
            if (controler.ToLower() == "menu")
            {
                <div class="row">
                    <div id="nav-for-menu" class="col-lg-3 col-sm-6" style="background-color: black">
                        @Html.Partial("_MenuRestaurantPartial")
                    </div>
                    
                    <div class="col-lg-9 col-sm-6" >
                        @RenderBody()
                    </div>
                </div>
            }
            else
            {
                @RenderBody()
            }
        }

    </div>
    <script src="~/Scripts/moment.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    @Scripts.Render("~/bundles/toastr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/bootstrapdatetimepicker")
    @Scripts.Render("~/bundles/myScript")
    @RenderSection("scripts", required: false)
</body>
</html>

RestaurantMvc.Web/Views/Shared/_MenuRestaurantPartial.cshtml
<article>
    <ul class="sidebar-nav">
        <li class="sidebar-brand">
           <p>Menu</p> 
        </li>
        <li>
            <a href="#">@Ajax.ActionLink("Zupy","Category","Menu",new {category="Zupy"}, new AjaxOptions {UpdateTargetId = "menuList"}) </a>
        </li>
        <li>
            <a href="#">@Ajax.ActionLink("Miesa", "Category","Menu", new { category = "Miesa" }, new AjaxOptions { UpdateTargetId = "menuList" })</a>
        </li>
        <li>
            <a href="#">@Ajax.ActionLink("Przystawki", "Category", "Menu", new { category = "Przystawki" }, new AjaxOptions { UpdateTargetId = "menuList" })</a>
        </li>
        <li>
            <a href="#">@Ajax.ActionLink("Ryby i owoce morza", "Category", "Menu", new { category = "Ryby i owoce morza" }, new AjaxOptions { UpdateTargetId = "menuList" })</a>
        </li>
        <li>
            <a href="#">@Ajax.ActionLink("Salaty", "Category", "Menu", new { category = "Salaty" }, new AjaxOptions { UpdateTargetId = "menuList" })</a>
        </li>
        <li>
            <a href="#">@Ajax.ActionLink("Makarony", "Category", "Menu", new { category = "Makarony" }, new AjaxOptions { UpdateTargetId = "menuList" })</a>
        </li>
        <li>
            <a href="#">@Ajax.ActionLink("Pizza", "Category", "Menu", new { category = "Pizza" }, new AjaxOptions { UpdateTargetId = "menuList" })</a>
        </li>
        <li>
            <a href="#">@Ajax.ActionLink("Desery", "Category", "Menu", new {category = "Desery"}, new AjaxOptions {UpdateTargetId = "menuList"})</a>
        </li>
        @if (User.IsInRole("admin") || User.IsInRole("staff") )
        {
            <li>
                <a href="#">@Html.ActionLink(" Add dishes", "AddCategory", "Menu", new { area = "" }, new { @class = "btn btn-warning" })</a>
            </li>
        }

       
    </ul>
</article>
        
  